chore: add pip log push on failure

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,7 +17,7 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install -r requirements.txt
+        pip install -r requirements.txt > pip_error.log 2>&1 || (git config user.email "bot@example.com" && git config user.name "bot" && git add pip_error.log && git commit -m "add pip log" && git push && exit 1)
         pip install pytest pytest-flask pytest-mock pytest-cov
     - name: Test with pytest
       run: |
